services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: my-rmq-container
    ports:
      - "8081:15672"
      - "8090:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq_data: